import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_url\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_thumbnail_filename\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_url\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_card_filename\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_url\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`media\` ADD \`sizes_gallery_filename\` text;`)
  await db.run(sql`CREATE INDEX \`media_sizes_thumbnail_sizes_thumbnail_filename_idx\` ON \`media\` (\`sizes_thumbnail_filename\`);`)
  await db.run(sql`CREATE INDEX \`media_sizes_card_sizes_card_filename_idx\` ON \`media\` (\`sizes_card_filename\`);`)
  await db.run(sql`CREATE INDEX \`media_sizes_gallery_sizes_gallery_filename_idx\` ON \`media\` (\`sizes_gallery_filename\`);`)
  await db.run(sql`ALTER TABLE \`events\` ADD \`reminders_sent\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`rsvps\` ADD \`cancel_token\` text;`)
  await db.run(sql`ALTER TABLE \`rsvps\` ADD \`cancelled\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`rsvps\` ADD \`cancelled_at\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`rsvps_cancel_token_idx\` ON \`rsvps\` (\`cancel_token\`);`)
  await db.run(sql`ALTER TABLE \`search\` ADD \`event_slug\` text;`)
  await db.run(sql`ALTER TABLE \`search\` ADD \`event_type\` text;`)
  await db.run(sql`ALTER TABLE \`search\` ADD \`start\` text;`)
  await db.run(sql`ALTER TABLE \`search\` ADD \`published\` integer;`)
  await db.run(sql`ALTER TABLE \`search\` ADD \`excerpt\` text;`)
  await db.run(sql`CREATE INDEX \`search_event_slug_idx\` ON \`search\` (\`event_slug\`);`)
  await db.run(sql`CREATE INDEX \`search_event_type_idx\` ON \`search\` (\`event_type\`);`)
  await db.run(sql`CREATE INDEX \`search_start_idx\` ON \`search\` (\`start\`);`)
  await db.run(sql`CREATE INDEX \`search_published_idx\` ON \`search\` (\`published\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`media_sizes_thumbnail_sizes_thumbnail_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`media_sizes_card_sizes_card_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`media_sizes_gallery_sizes_gallery_filename_idx\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_url\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_width\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_height\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_filesize\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_thumbnail_filename\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_url\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_width\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_height\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_filesize\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_card_filename\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_url\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_width\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_height\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_filesize\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`sizes_gallery_filename\`;`)
  await db.run(sql`DROP INDEX \`rsvps_cancel_token_idx\`;`)
  await db.run(sql`ALTER TABLE \`rsvps\` DROP COLUMN \`cancel_token\`;`)
  await db.run(sql`ALTER TABLE \`rsvps\` DROP COLUMN \`cancelled\`;`)
  await db.run(sql`ALTER TABLE \`rsvps\` DROP COLUMN \`cancelled_at\`;`)
  await db.run(sql`DROP INDEX \`search_event_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`search_event_type_idx\`;`)
  await db.run(sql`DROP INDEX \`search_start_idx\`;`)
  await db.run(sql`DROP INDEX \`search_published_idx\`;`)
  await db.run(sql`ALTER TABLE \`search\` DROP COLUMN \`event_slug\`;`)
  await db.run(sql`ALTER TABLE \`search\` DROP COLUMN \`event_type\`;`)
  await db.run(sql`ALTER TABLE \`search\` DROP COLUMN \`start\`;`)
  await db.run(sql`ALTER TABLE \`search\` DROP COLUMN \`published\`;`)
  await db.run(sql`ALTER TABLE \`search\` DROP COLUMN \`excerpt\`;`)
  await db.run(sql`ALTER TABLE \`events\` DROP COLUMN \`reminders_sent\`;`)
}
